-- Migration: create_id_generator
-- Description: Create ID sequence table and next_id function for distributed IDs
-- Created: 2026-01-25 00:00:01

Migration.up = function()
    Schema.create("users", function(table)
        table:id():primary()
        table:string("first_name", 125)
        table:string("last_name", 125)
        table:string("username", 125)
        table:string("email", 255)
        table:string("password_hash", 255)
        table:timestamp("email_confirmed_at")
        table:timestamp("invited_at")
        table:string("confirmation_token", 255)
        table:timestamp("confirmation_sent_at")
        table:string("recovery_token", 255)
        table:timestamp("recovery_sent_at")
        table:string("email_change_token_new", 255)
        table:string("email_change", 255)
        table:timestamp("email_change_sent_at")
        table:string("phone", 255)
        table:timestamp("phone_confirmed_at")
        table:string("phone_change", 255)
        table:string("phone_change_token", 255)
        table:timestamp("phone_change_sent_at")
        table:timestamp("confirmed_at")
        table:string("email_change_token_current", 255)
        table:boolean("email_change_confirm_status")
        table:string("otp_code", 200)
        table:timestamp("otp_sent_at")
        table:timestamp("banned_until")
        table:string("reauthentication_token", 255)
        table:timestamp("reauthentication_sent_at")
        table:string("avatar_url", 255)
        table:json("metadata")
        table:json("attributes")
        table:timestamp("last_sign_in_at")
        table:boolean("is_super_admin")
        table:boolean("is_sso_user")
        table:timestamps()
        table:softDeletes()
    end)
end

Migration.down = function()
    Schema.dropIfExists("test_users")
end
