#!/bin/bash

# Lista de todos los componentes
components=(
    "accordion"
    "alert-dialog"
    "alert"
    "aspect-ratio"
    "avatar"
    "badge"
    "breadcrumb"
    "button-group"
    "button"
    "calendar"
    "card"
    "carousel"
    "chart"
    "checkbox"
    "collapsible"
    "combobox"
    "command"
    "context-menu"
    "data-table"
    "date-picker"
    "dialog"
    "drawer"
    "dropdown-menu"
    "empty"
    "field"
    "form"
    "hover-card"
    "input-group"
    "input-otp"
    "input"
    "item"
    "kbd"
    "label"
    "menubar"
    "native-select"
    "navigation-menu"
    "pagination"
    "popover"
    "progress"
    "radio-group"
    "range-calendar"
    "resizable"
    "scroll-area"
    "select"
    "separator"
    "sheet"
    "sidebar"
    "skeleton"
    "slider"
    "sonner"
    "spinner"
    "switch"
    "table"
    "tabs"
    "textarea"
    "toggle-group"
    "toggle"
    "tooltip"
    "typography"
)

echo "Instalando todos los componentes de shadcn-svelte..."

for comp in "${components[@]}"
do
    echo "Instalando $comp..."
    pnpx shadcn-svelte add $comp
done

echo "✅ Todos los componentes instalados."
